NEW = 'new'
IN_PROGRESS = 'in_progess'
DELIVERED = 'delivered'
SHIPPER = 'shipper'
INDIVIDUAL = 'individual'
UNDER_CONSIDERATION = 'under_consideration'
REJECTED = 'rejected'
ACCEPTED = 'accepted'
ASSIGNED = 'assigned'
COMPLETED = 'completed'
PENDING = 'pending'
ON_HOLD = 'ob_hold'
HOME = ('Home', 'home_url')
DASHBOARD = ('Dashboard', 'dashboard_url', 'user.username')
MY_PROFILE = ('Profile', 'user_profile', 'user.username')
JOBS = ('Assign Job', 'jobs_url')
ADD_JOB = ('Post Job', 'job_posting_url')
AVAILABLE_JOBS = ('Available', 'available_url')
JOBS_IN_PROGRESS = ('In Progress', 'user_profile', 'current_jobs_tab')
JOBS_COMPLETED = ('Completed', 'user_profile', 'completed_jobs_tab')
POST_JOB = ('Post Job', 'job_posting_url')
USERS = ('Members', 'registered_users_url')
SERVICE = ('Services', 'services_url')
CONTACT_US = ('Contact Us', 'contact_us_url')
NOTIFICATIONS = ('Message Notifications', 'notifications_url')
ARTISAN = 'artisan'
CUSTOMER = 'customer'
HANDYMAN_ADMIN = 'handyman_admin'
SME = 'sme'
